sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: TAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: 6k1br0z8ga0Ixv3nxbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx1633ef13eac1dc11
    secret: 9dcbc21893df036edcde346645d1c1bd
    mchid: 561414331
    mchSerialNo: B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: ZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://17968c0.r1.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://17968c0.r1.cpolar.top/notify/refundSuccess
  shop:
    address: 江苏省南京市江宁区金陵科技学院北区2幢
  baidu:
    ak: B3B3Dwx1633ef13eac1dc11BAF8DE9CC7CF407606